name: Cypress tests
on: push
jobs:
  cypress-run:
    name: Cypress run
    runs-on: ubuntu-22.04
    container:
      image: cypress/browsers:node-22.11.0-chrome-130.0.6723.69-1-ff-132.0-edge-130.0.2849.56-1
      options: --user 1001
    strategy:
      # don't fail the entire matrix on failure
      fail-fast: false
      matrix:
        # run copies of the current job in parallel
        containers: [1]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        #https://github.com/marketertechnologies/cypress-github-action
        uses: cypress-io/github-action@v6
        with:
          #record: true
          #parallel: true
          start: npx cypress run
          browser: chrome
          spec: cypress/e2e/ui-tests/*.cy.{js,jsx,ts,tsx}
        env:
          HOME: /root
          USER:  ${{ secrets.USER }}
          PASSWORD: ${{ secrets.PASSWORD }}
          USER_ADM:  ${{ secrets.USER_ADM }}
          PASSWORD_ADM: ${{ secrets.PASSWORD_ADM }}
          BASE_URL_WEB: ${{ secrets.BASE_URL_WEB }} 
          BASE_URL_API: ${{ secrets.BASE_URL_API }}
            
      - name: Uploading artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-execution-report
          path: cypress/reports/html
          retention-days: 30